### ISSUE TITLE
Build Failed on suse 13.2

### ISSUE THREAD

**Issue by Hesam-Naderi-Dehkordi** [lucwillems/JavaLinuxNet#8]
Hi there. After doing all you said step by step, get the following error on opensuse 13.2 64bit

Results :

Failed tests:   testPerformanceMultibleClients(org.it4y.integration.IT_TProxyListenerTest): expected:<1000> but was:<0>

Tests in error: 
  testTProxyConnection(org.it4y.integration.IT_TProxyListenerTest): connect timed out
  testIOError(org.it4y.integration.IT_TProxyListenerTest): connect timed out

Tests run: 107, Failures: 1, Errors: 2, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
........

**Comment by lucwillems** [comment]
Check if you have the opensuse Firewall or other IPTables configuration running.
the TProxy test will intercept TCP connections from other src & dst ip's.
iptables causes the connections to fail.

 luc

**Comment by Hesam-Naderi-Dehkordi** [comment]
I was doing a big mess.
Suse firewall was enabled in yast2 control setting. You must disable it before running test script.

Thanks again
